# Generated by Django 2.2.4 on 2020-11-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndLaborApp', '0002_scheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTODay', models.DateField()),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
                ('PTOHours', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PTOreq', to='TimeAndLaborApp.User')),
            ],
        ),
    ]
