# Generated by Django 2.2.4 on 2021-01-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndLaborApp', '0003_timeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='logging',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaidTimeOff', models.IntegerField()),
                ('PtoRemainingBalance', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('UserPTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyTimeOff', to='TimeAndLaborApp.User')),
            ],
        ),
    ]
