# Generated by Django 2.2 on 2021-01-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndLaborApp', '0005_auto_20210107_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Pto',
            field=models.IntegerField(default=144),
            preserve_default=False,
        ),
    ]
