# Generated by Django 2.2 on 2021-01-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndLaborApp', '0006_auto_20210116_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requested',
            name='PtoRemainingBalance',
        ),
    ]
