# Generated by Django 2.2 on 2021-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndLaborApp', '0007_remove_requested_ptoremainingbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='clock_in',
            field=models.TimeField(),
        ),
    ]
