# Generated by Django 2.2 on 2021-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeAndLaborApp', '0010_auto_20210116_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
